[package]
name = "bitcoinrs"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]

[dependencies]
bitcoinrs_proto = { path = "proto" }
bitcoinrs_crypto = { path = "crypto" }

[workspace]
members = ["proto", "crypto"]
