[package]
name = "bitcoinrs_crypto"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]

[dependencies]
bitcoinrs_bytes = { path = "../bitcoinrs_bytes" }

[dev-dependencies]
openssl = "0.10"
rand = "0.4"
