[package]
name = "bitcoinrs_net"
version = "0.1.0"
authors = ["AtsukiTak <takatomgoo@gmail.com>"]

[dependencies]
bitcoinrs_bytes = { path = "../bitcoinrs_bytes" }
bitcoinrs_crypto = { path = "../bitcoinrs_crypto" }

[[example]]
name = "send_msg"
path = "examples/send_msg.rs"
